services:
  php:
    image: bilet-satin-alma-php
    container_name: bilet-php
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: bilet-nginx
    ports:
      - "8282:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx:/etc/nginx/conf.d:ro
    depends_on:
      - php
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
                   