version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./src/uploads:/var/www/html/uploads
      - ./src/static:/var/www/html/static
    networks:
      - app-network
    environment:
      - DB_PATH=/var/www/html/ticket.db
      - UPLOADS_DIR=/var/www/html/uploads
      - STATIC_DIR=/var/www/html/static

networks:
  app-network:
    driver: bridge